### ISSUE TITLE
Python Basic Example: Internal Error

### ISSUE THREAD

**Issue by cynthia-w** [NetLogo/Python-Extension#19]
After pressing "setup", I get the following error:

NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.IllegalStateException
 at scala.util.matching.Regex$MatchIterator.ensure(Regex.scala:850)
 at scala.util.matching.Regex$MatchIterator.groupCount(Regex.scala:869)
 at org.nlogo.extensions.py.PythonBinary$.$anonfun$fromFile$2(PythonExtension.scala:150)
 at scala.Option.flatMap(Option.scala:188)
 at org.nlogo.extensions.py.PythonBinary$.fromFile(PythonExtension.scala:148)
 at org.nlogo.extensions.py.PythonSubprocess$.$anonfun$pythons$3(PythonExtension.scala:253)
 at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
 at org.nlogo.extensions.py.PythonSubprocess$.pythons(PythonExtension.scala:253)
 at org.nlogo.extensions.py.PythonSubprocess$.$anonfun$python3$4(PythonExtension.scala:246)
 at scala.Option.orElse(Option.scala:306)
 at org.nlogo.extensions.py.PythonSubprocess$.python3(PythonExtension.scala:246)
 at org.nlogo.extensions.py.PythonSubprocess$.anyPython(PythonExtension.scala:248)
 at org.nlogo.extensions.py.PythonExtension.$anonfun$load$5(PythonExtension.scala:512)
 at org.nlogo.extensions.py.FindPython.report(PythonExtension.scala:590)
 at org.nlogo.extensions.py.FindPython.report(PythonExtension.scala:585)
 at org.nlogo.prim._externreport.report(_externreport.java:31)
 at org.nlogo.nvm.Argument.unsafeGet(Argument.scala:33)
 at org.nlogo.nvm.Argument.getString(Argument.scala:111)
 at org.nlogo.extensions.py.SetupPython$.$anonfun$perform$1(PythonExtension.scala:549)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
 at scala.collection.TraversableLike.map(TraversableLike.scala:237)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
 at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
 at org.nlogo.extensions.py.SetupPython$.perform(PythonExtension.scala:549)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Python Basic Example

09:22:25.076 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
09:22:25.060 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:22:25.060 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:25.060 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:25.060 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:25.060 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:25.060 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:22:24.871 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
09:22:24.856 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:22:24.856 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

**Comment by cynthia-w** [comment]
Thank you so much for your help Aaron! A detailed response and easy to follow. Deeply appreciate it. Have a great day!!

**Comment by qiemem** [comment]
Reopening because this does appear to be a bug, even if there's a workaround.

**Comment by brandesNW** [comment]
I recently encountered a similar problem while running the extension tests in sbt on MacOS

`netlogo/testOnly *TestExtensions  -- -z "py::np-array-convert-to-lists-python3"`
resulted in the error

> py::np-array-convert-to-lists-python3 *** FAILED ***
> [info]   org.nlogo.headless.LanguageTestException: The test errored on the following line: py:runresult "np.array([1,2,3])"
> [info]   ...
> [info]   Cause: org.nlogo.nvm.WrappedExtensionException: Extension exception: module 'numpy' has no attribute 'array'
> [info]   at org.nlogo.prim._externreport.report(_externreport.java:35)

I found this explanation in [StackOverflow](https://stackoverflow.com/questions/36530726/using-numpy-module-object-has-no-attribute-array)

> You are most likely having a file called numpy.py in your working directory which shadows the real numpy module. Rename that file and remove its numpy.pyc file.

I was also able to reproduce the problem with the following simple NetLogo program:

```
extensions [ py ]
to setup
  py:setup py:python
  py:run "import numpy as np"
  show py:runresult "np.array([1,2,3])"
end
```

Both problems disappeared when I used the NetLogo _Python -> Configure_ option to set the path for the Python 3 executable.

When I tested the problem in Windows, I got an error message very similar to cynthia-w's.

- NetLogo is unable to supply you with more details about this error.  Please report the problem 
-  at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
- contents of this window into your report. 
- 
- 
- java.lang.IllegalStateException
-  at scala.util.matching.Regex$MatchIterator.ensure(Regex.scala:850)
-  at scala.util.matching.Regex$MatchIterator.groupCount(Regex.scala:869)
-  at org.nlogo.extensions.py.PythonBinary$.$anonfun$fromFile$2(PythonExtension.scala:150)
-  at scala.Option.flatMap(Option.scala:271)
-  at org.nlogo.extensions.py.PythonBinary$.fromFile(PythonExtension.scala:148)
-  at org.nlogo.extensions.py.PythonSubprocess$.$anonfun$pythons$3(PythonExtension.scala:248)
-  at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
-  at org.nlogo.extensions.py.PythonSubprocess$.pythons(PythonExtension.scala:248)
-  at org.nlogo.extensions.py.PythonSubprocess$.$anonfun$python3$4(PythonExtension.scala:241)
-  at scala.Option.orElse(Option.scala:447)
-  at org.nlogo.extensions.py.PythonSubprocess$.python3(PythonExtension.scala:241)
-  at org.nlogo.extensions.py.PythonSubprocess$.anyPython(PythonExtension.scala:243)
-  at org.nlogo.extensions.py.PythonExtension.$anonfun$load$5(PythonExtension.scala:507)
-  at org.nlogo.extensions.py.FindPython.report(PythonExtension.scala:613)
-  at org.nlogo.extensions.py.FindPython.report(PythonExtension.scala:608)
-  at org.nlogo.prim._externreport.report(_externreport.java:31)
-  at org.nlogo.nvm.Argument.unsafeGet(Argument.scala:33)
-  at org.nlogo.nvm.Argument.getString(Argument.scala:120)
-  at org.nlogo.extensions.py.SetupPython$.$anonfun$perform$1(PythonExtension.scala:543)
-  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
-  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
-  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
-  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
-  at scala.collection.TraversableLike.map(TraversableLike.scala:285)
-  at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
-  at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
-  at org.nlogo.extensions.py.SetupPython$.perform(PythonExtension.scala:543)
-  at org.nlogo.prim._extern.perform(_extern.java:36)
-  at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
-  at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
-  at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
-  at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
-  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
-  at scala.util.control.Exception$Catch.apply(Exception.scala:228)
-  at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
-  at org.nlogo.job.JobThread.run(JobThread.scala:66)
- 
- NetLogo 6.2.0
- main: org.nlogo.app.AppFrame
- thread: JobThread
- OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
- operating system: Windows 10 10.0 (amd64 processor)
- Scala version 2.12.12
- JOGL: (3D View not initialized)
- OpenGL Graphics: (3D View not initialized)
- model: python-array
- 
- 01:32:40.523 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
- 01:32:40.523 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
- 01:32:40.000 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
- 01:32:40.000 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
- 01:32:39.900 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
- 01:32:39.799 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
- 01:32:39.599 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
- 01:32:39.394 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
- 01:32:39.179 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
- 01:32:38.978 ModelSavedEvent (org.nlogo.app.MenuBar) AWT-EventQueue-0

**Comment by brandesNW** [comment]
I think we should consider the following change to the py extension - If a path to the python executable is not configured, we do not attempt to find one. Instead we issue a message explaining that the path must be set, and include a link to the documentation.

It appears that in the current situation users are left with a cryptic error message. They may also find that the extension works for some models and not others.

**Comment by LaCuneta** [comment]
Closing this as a duplicate of #23.  Really this one was first, but that's the one I saw when I applied the fixes.  See my comments in that issue for more info on the changes released in 0.5.1.
