### ISSUE TITLE
Can't run examples with Netlogo 6.2.2

### ISSUE THREAD

**Issue by bennycui99** [NetLogo/Python-Extension#23]
This message came out when I tried to set up in the Flocking Cluster example:
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.IllegalStateException
 at scala.util.matching.Regex$MatchIterator.ensure(Regex.scala:850)
 at scala.util.matching.Regex$MatchIterator.groupCount(Regex.scala:869)
 at org.nlogo.extensions.py.PythonBinary$.$anonfun$fromFile$2(PythonExtension.scala:150)
 at scala.Option.flatMap(Option.scala:271)
 at org.nlogo.extensions.py.PythonBinary$.fromFile(PythonExtension.scala:148)
 at org.nlogo.extensions.py.PythonSubprocess$.$anonfun$pythons$3(PythonExtension.scala:248)
 at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
 at org.nlogo.extensions.py.PythonSubprocess$.pythons(PythonExtension.scala:248)
 at org.nlogo.extensions.py.PythonSubprocess$.$anonfun$python3$4(PythonExtension.scala:241)
 at scala.Option.orElse(Option.scala:447)
 at org.nlogo.extensions.py.PythonSubprocess$.python3(PythonExtension.scala:241)
 at org.nlogo.extensions.py.PythonSubprocess$.anyPython(PythonExtension.scala:243)
 at org.nlogo.extensions.py.PythonExtension.$anonfun$load$5(PythonExtension.scala:507)
 at org.nlogo.extensions.py.FindPython.report(PythonExtension.scala:613)
 at org.nlogo.extensions.py.FindPython.report(PythonExtension.scala:608)
 at org.nlogo.prim._externreport.report(_externreport.java:31)
 at org.nlogo.nvm.Argument.unsafeGet(Argument.scala:33)
 at org.nlogo.nvm.Argument.getString(Argument.scala:120)
 at org.nlogo.extensions.py.SetupPython$.$anonfun$perform$1(PythonExtension.scala:543)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
 at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
 at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
 at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
 at scala.collection.TraversableLike.map(TraversableLike.scala:286)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
 at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
 at org.nlogo.extensions.py.SetupPython$.perform(PythonExtension.scala:543)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.2.2
main: org.nlogo.app.AppFrame
thread: JobThread
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.15
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Flocking Clusters

04:18:56.877 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
04:18:56.865 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:18:56.436 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:18:56.436 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:18:56.436 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:18:56.436 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:18:56.436 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:18:56.435 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:18:56.435 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:18:56.435 TickStateChangeEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread

**Comment by LaCuneta** [comment]
@bennycui99 Thanks for reporting this issue and sorry you ran into it.  

It looks like the extension is having trouble parsing the version string for Python, meaning it's either not installed as expected or it might be in a different format on your system than the code expects.  We should definitely give a better error message in this case, but I want to make sure there isn't a deeper issue with the Python version parser we're using.

Do you know which version of Python you have installed on your system?  Did you set a path to your Python executable through the **Python** > **Configure** menu item?  If you can open a Command Prompt and run `python -v` for me and report the result, that would be helpful.  It might be `python2 -v` or `python3 -v` if just `python` doesn't work.  If you know which you have, you can just try running that.

**Comment by Landa94** [comment]
Hello @LaCuneta, I am having the same problem as @bennycui99. I am currently using Python 3.9.7. Do you have any clues of what might be happening? I would note have any issue downgrading Python if you know which version is compatible with Netlogo for the extension. Thanks!

**Comment by LaCuneta** [comment]
With a couple recent changes, you should now see a much clearer message about what to do when the Python executable isn't found, or the Python executable version doesn't match what is expected.  It will ask you to just set it manually via the Python > Configure menu.  These changes are released as version 0.5.1 in the NetLogo extensions library, and you can update through [the extensions manager in NetLogo](https://ccl.northwestern.edu/netlogo/docs/extension-manager.html).

I think this should cover most cases here, so I'm closing this issue.  But if anyone sees this and has a case where manually setting the executable is failing, please feel free to leave a new comment or open a new issue with your system details (OS, Python version, path to executable, etc).
